[build]
  publish   = "."
  functions = "functions"

# Send API calls to Netlify Functions
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200

# SPA history fallback: serve index.html for all other routes
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  
toml [build] publish = "." # or your public folder functions = "functions"
